/*
 * This file is generated by jOOQ.
 */
package bbm.jooq;


import bbm.jooq.tables.Test;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.test</code>.
     */
    public static final Test TEST_ = Test.TEST_;
}
